-- Business Problems and Advance analysis

/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/

--updating table
alter table order_items
add column total_price float;
update order_items
set total_price = quantity * price_per_unit;

select 
	product_name,
	sum(quantity) as total_quantity_sold,
	round(cast(sum(total_price) as decimal),2) as total_sales_value
from products p
inner join order_items oi
on oi.product_id = p.product_id
group by product_name
order by total_sales_value desc
limit 10;


/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/

select
	*,
	concat(round((total_sales_value/sum(total_sales_value) over())*100,2),'%') Percent_Contribution
from(
	select
		c.category_id,
		category_name,
		round(cast(sum(total_price) as decimal),2) as total_sales_value
	from products p
	inner join order_items oi
	on oi.product_id = p.product_id
	inner join category c
	on p.category_id = c.category_id
	group by category_name,c.category_id
)
order by total_sales_value desc;

/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/

select
	*,
	round(total_value/orders,2) as avg_order_value
from(
	select
		c.customer_id,
		concat(first_name,' ',last_name) as full_name,
		round(cast(sum(total_price) as decimal),2) as total_value,
		count(oi.order_id) as orders
	from customers c
		inner join orders o
		on o.customer_id = c.customer_id
		inner join order_items oi
		on oi.order_id = o.order_id
	group by c.customer_id,full_name
)
where orders > 5
order by avg_order_value desc;

/*
4. Monthly Sales Trend
Query monthly total sales over the past years.
Challenge: Display the sales trend, grouping by month, return current_month sale with last month sale!
*/

select
	month,
	sales as cm_sales,
	lag(sales,1,0) over(order by month asc) as pm_sales,
	sales - lag(sales,1,0) over(order by month asc) as sales_trend
from (
select
	extract('month' from order_date) as month,
	round(cast(sum(total_price) as decimal),2) as sales
from orders o
inner join order_items oi
on o.order_id = oi.order_id
group by month
order by month
);

-- alternative


with t as(
select max(order_date) as max_date from orders
)

select
	*,
	lag(cm_sales,1,0) over(order by year, month asc) as pm_sales,
	cm_sales - lag(cm_sales,1,0) over(order by year, month asc) as sales_trend,
	concat(round(coalesce((cm_sales/lag(cm_sales) over(order by year,month asc) -1)*100,0),2),'%') as sales_growth
from (
select
	extract('month' from order_date) as month,
	extract('year' from order_date) as year,
	round(cast(sum(total_price) as decimal),2) as cm_sales
from orders o
inner join order_items oi
on o.order_id = oi.order_id
where order_date >= (select max_date from t) - interval '1 year'
group by month, year
)
order by year, month;


/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details
*/

select c.* from customers c
left join orders o
on c.customer_id = o.customer_id
where o.customer_id is null;


/*
6. Leat-Selling Categories by State
Identify the least-selling category for each state.
Challenge: Include the total sales for that category within each state.
*/

select * from(
select
	state,
	category_name,
	round(sum(total_price::numeric),2) as sales,
	row_number() over(partition by state order by round(sum(total_price::numeric),2) asc) as ranked
from customers c
inner join orders o
on c.customer_id = o.customer_id
inner join order_items oi
on o.order_id = oi.order_id
inner join products p
on oi.product_id = p.product_id
inner join category ct
on p.category_id = ct.category_id
group by state, category_name
) where ranked = 1;


/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/

select
	*,
	dense_rank() over(order by sales desc) as ranks
from(
select
	c.customer_id,
	concat(first_name,' ',last_name) as full_name,
	sum(total_price::numeric) as sales
from customers c
inner join orders o
on c.customer_id = o.customer_id
inner join order_items oi
on o.order_id = oi.order_id
group by 1,2
);

/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/


select 
	i.inventory_id,
	p.product_id,
	product_name,
	stock,
	last_stock_date,
	warehouse_id
from products p
inner join inventory i
on p.product_id = i.product_id
where stock < 10
order by product_id
;

/*
9. Shipping Delays
Identify orders where the shipping date is later than 7 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/

select 
	concat(first_name,' ',last_name) as full_name,
	o.order_id,
	order_date,
	shipping_date,
	shipping_provider,
	shipping_date-order_date as shippment_days
from shipping s
inner join orders o 
on o.order_id = s.order_id
inner join customers c
on c.customer_id = o.customer_id
where shipping_date-order_date > 7;

/*
10. Payment Success Rate
Calculate the percentage on successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

select
	*,
	round(sum(total_payments) over(partition by payment_status)/ sum(total_payments) over() *100,2) as payment_rate
from (
select
	payment_status,
	count(*)::numeric as total_payments
from payments p
inner join orders o
on p.order_id = o.order_id
group by payment_status);

/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/

with top_sellers as(
select 
	seller_name,
	round(sum(total_price::numeric),2) as total_sales
from sellers s
inner join orders o
on s.seller_id = o.seller_id
inner join order_items as oi
on oi.order_id = o.order_id 
group by seller_name
order by total_sales desc
limit 5
),

seller_report as(
select 
		s.seller_id,
		s.seller_name,
		order_status,
		count(o.order_id)::numeric as total_orders
	from sellers s
	inner join orders o
	on s.seller_id = o.seller_id
	inner join order_items as oi
	on oi.order_id = o.order_id
	inner join top_sellers t
	on t.seller_name = s.seller_name
	where order_status not in ('Inprogress','Returned')
	group by s.seller_name,s.seller_id,order_status
)

select
	*,
	round(completed_orders/total_order*100,2) successful_rate
from(
select 
	seller_id,
	seller_name,
	sum(case when order_status = 'Completed' then total_orders else 0 end) as completed_orders,
	sum(case when order_status = 'Cancelled' then total_orders else 0 end) as cancelled_orders,
	sum(total_orders) as total_order
from seller_report
group by seller_id,seller_name
);

/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge Rank products by their profit margin, showing highest to lowest.
*/

select
	*,
	dense_rank() over(order by profit_margin desc) as Product_Rank
from (
	select
		product_name,
		price,
		cogs,
		price - cogs as Profit,
		round(((price - cogs)/price*100)::numeric,2) as profit_margin
	from products
);

/*
13. Most Returned Products
Query the top 18 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/

select
	*,
	round(returns/total_units*100,2) as return_rate
from (
select 
	p.product_id,
	product_name,
	sum(quantity)::numeric as total_units,
	sum(case when order_status = 'Returned' then quantity else 0 end)::numeric as returns
from products p
inner join order_items oi
on oi.product_id = p.product_id
inner join orders o
on o.order_id = oi.order_id
group by p.product_id, product_name)
order by returns desc
limit 18;

/*
14. IDENTITY customers into returning or new
if the customer has done more than 2 return categorize them as returning otherwise new
Challenge: List customers id, name, total orders, total returns
*/


select
	*,
	case when total_returns > 2 then 'Returning' else 'New' end as categorized_customers
from(
select 
	c.customer_id,
	concat(first_name,' ',last_name) as full_name,
	count(order_id) as Total_orders,
	sum(case when order_status = 'Returned' then 1 else 0 end) as total_returns
from customers c
inner join orders o
on c.customer_id = o.customer_id
group by 1,2
)

/*
15. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/


select * from (
select
	c.customer_id,
	concat(first_name,' ',last_name) as full_name,
	state,
	count(o.order_id) as total_orders,
	sum(total_price) as total_sales,
	dense_rank() over(partition by state order by count(o.order_id) desc) as ranked
from customers c
inner join orders o
on c.customer_id = o.customer_id
inner join order_items oi
on oi.order_id = o.order_id
group by 1,2,3
) where ranked <= 5
;

/*
16. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average delivery time for each provider.
*/

select 
	shipping_provider,
	sum(total_price) as total_revnue,
	count(o.order_id) as total_orders,
	round(avg(shipping_date - order_date)::numeric,2) as avg_delivery_time
from shipping s
inner join orders o
on o.order_id = s.order_id
inner join order_items oi
on o.order_id = oi.order_id
group by 1;


/*
17. Top 20 product with highest decreasing revenue ratio compare to last year (2022) and current year (2023)
Challenge: Return product_id, product_name, category_name, 2022 revenue and 2023 revenue decrease ratio at end Round the result
Note: Decrease ratio cr-ls/ls* 100 (cs current_year ls=last_year)
*/


select
	*,
	round(((revenue_2023/nullif(revenue_2022,0) - 1)*100)::numeric,2) as decrease_ratio
from(
	select
		p.product_id,
		product_name,
		category_name,
		sum(case when extract('year' from order_date) = 2022 then total_price else 0 end)::numeric as Revenue_2022,
		sum(case when extract('year' from order_date) = 2023 then total_price else 0 end)::numeric as Revenue_2023
	from products p
	inner join order_items oi
	on p.product_id = oi.product_id
	inner join orders o
	on o.order_id = oi.order_id
	inner join category c
	on c.category_id = p.category_id
	group by 1,2,3
)
order by decrease_ratio asc
limit 20;




